### ISSUE TITLE
def.scala.version=2.8.1 (build properties)

### ISSUE THREAD

**Issue by afwlehmann** [scalala/Scalala#12]
Hi,

apparently I'm cluttering the issues today, my honest apologies! However, it seems like `def.scala.version=2.8.1` in `project/build.properties` should be replaced with `def.scala.version=2.7.7` since sbt 0.7.x works with 2.7.7 only.
Although in my case everything built just fine with the current setting (I'm aware that it's not `build.scala.version`), I wasn't able to use sbt-idea until I switched back to 2.7.7. This problem might arise with other sbt processors, too.

Regards,
Alexander

**Comment by dramage** [comment]
Fixed in https://github.com/scalala/Scalala/commit/1286be9f2be87b073b5ff842949037f6604019bd
