### ISSUE TITLE
Error while trying to multiply a vector-row with a matrix

### ISSUE THREAD

**Issue by SandroGrzicic** [scalala/Scalala#13]
Hi,

I've been trying this for hours but to no avail.

I'm getting the following compile-time error:
Could not find a way to scalala.operators.OpMul values of type scalala.tensor.dense.DenseVectorRow[Int] and scalala.tensor.dense.DenseMatrix[Int]

.. when I try to do this:

``` scala
DenseVector(1, 1).t :* DenseMatrix((1, 1), (2, 2))
```

Basically, I'm matrix-multiplying a 2-column vector with a 2x2 matrix. I don't understand why I'm getting the specified error.

I thought maybe it's because I'm multiplying a vector with a matrix. Then I tried this:

``` scala
DenseMatrix((1, 1)) :* DenseMatrix((1, 1), (2, 2))
```

That compiles, but yields the following runtime error:

[error] scalala.tensor.domain.DomainException: Incompatible domain: TableDomain(2,2)
[error]     at scalala.tensor.DomainFunction$class.checkDomain(DomainFunction.scala:54)
[error]     at scalala.tensor.mutable.MatrixTranspose$Impl.checkDomain(MatrixTranspose.scala:57)
[error]     at scalala.tensor.Tensor$$anon$15.joinBothNonZero(Tensor.scala:577)
[error]     at scalala.tensor.Tensor$$anon$4.apply(Tensor.scala:616)
[error]     at scalala.operators.NumericOps$class.$colon$times(Ops.scala:42)
[error]     at scalala.tensor.mutable.MatrixTranspose$Impl.$colon$times(MatrixTranspose.scala:57)
[error]     at hr.sandrogrzicic.grafika.test.ScalalaTest$.main(ScalalaTest.scala:17)
[error]     at hr.sandrogrzicic.grafika.test.ScalalaTest.main(ScalalaTest.scala)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]     at java.lang.reflect.Method.invoke(Unknown Source)
[error]     at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:81)
[error]     at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
[error]     at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:86)
[error]     at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:81)
[error]     at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:86)
[error]     at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:83)
[error]     at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

I'm using Scala 2.9.0.RC1 (but I set SBT to use 2.8.1 using ++2.8.1 because with 2.9.0.RC1 I get runtime RichInt-related errors in Scalala.. but that's another issue.) with SBT 0.7.5.

How do I multiply a vector-row with a matrix using scalala?

**Comment by dramage** [comment]
You're using the wrong operator. For shaped multiplication you need to use `*` instead of `:*`.  This is true in every linear algebra library, e.g. R's `%*%` versus `*` and Matlab's `*` versus `.*`

``` scala

scala> val a = scalala.tensor.dense.DenseMatrix((1,1))
m: scalala.tensor.dense.DenseMatrix[Int] = 1  1  

scala> val b = scalala.tensor.dense.DenseMatrix((1,1),(2,2))
b: scalala.tensor.dense.DenseMatrix[Int] = 
1  1  
2  2  

scala> a * b
res0: scalala.tensor.dense.DenseMatrix[Int] = 3  3  
```

**Comment by dramage** [comment]
Same goes for row-matrix multiplication:

``` scala
scala> DenseVector(1, 1).t :* DenseMatrix((1, 1), (2, 2))
<console>:9: error: Could not find a way to scalala.operators.OpMul values of type scalala.tensor.dense.DenseVectorRow[Int] and scalala.tensor.dense.DenseMatrix[Int]
       DenseVector(1, 1).t :* DenseMatrix((1, 1), (2, 2))
                           ^

scala> DenseVector(1, 1).t * DenseMatrix((1, 1), (2, 2)) 
res2: scalala.tensor.dense.DenseVectorRow[Int] = 3 3
```

**Comment by SandroGrzicic** [comment]
Thanks!
