### ISSUE TITLE
det() method is incorrect

### ISSUE THREAD

**Issue by lancelet** [scalala/Scalala#21]
The det() method incorrectly interprets the output of the LU() method to count the number of swapped rows of the matrix.  This can be illustrated with an example:

> G = Matrix((-1.,1.,-1.),(1.,2.,3.),(3.,-10.,1.))
> det(G)
>   8.0
> The correct determinant is -8.0

A pull request to fix the problem will follow shortly.

**Comment by dramage** [comment]
Merged
