### ISSUE TITLE
Missing dependencies: jfree#jcommon, netlib#netlib-java, netlib#arpack-combo

### ISSUE THREAD

**Issue by yang** [scalala/Scalala#28]
I'm getting these errors from sbt:

```
[warn]  module not found: jfree#jcommon;1.0.16
[warn]  module not found: netlib#netlib-java;0.9.3
[warn]  module not found: netlib#arpack-combo;0.1
```

I tried Googling for the first one and found a random repo that had it, and while I could do the same for the remaining ones, I was hoping there's a better way or something I'm missing.

**Comment by yang** [comment]
Found the artifacts in scalanlp.org. Suggest adding this to https://github.com/scalala/Scalala/wiki/QuickStart, since I thought the documentation on http://www.scalanlp.org/?page_id=6 was out of date given that the repo there only hosts scalala up to 0.3.

**Comment by bwanab** [comment]
Scalala is great! But, I had the same problem as Yang. Here is my minimal project file to get scalala working (this is for sbt 0.7.4):

  val scalalatools = "Scala Tools Snapshots" at "http://scala-tools.org/repo-snapshots/"
  val scalanlp = "ScalaNLP" at "http://repo.scalanlp.org/repo/"
  override def libraryDependencies = Set(
    "org.scalala" %% "scalala" % "1.0.0.RC2-SNAPSHOT"
  ) ++ super.libraryDependencies

**Comment by dramage** [comment]
Thanks, folks.  I updated the QuickStart accordingly.
