### ISSUE TITLE
Update to use the current SBT

### ISSUE THREAD

**Issue by emchristiansen** [scalala/Scalala#29]
SBT 0.10.x uses a [new configuration style](https://github.com/harrah/xsbt/wiki/Migrating-from-SBT-0.7.x-to-0.10.x). Perhaps the build configs should be updated? More importantly, it's not clear how to depend on the current scalala from an sbt 0.10.x client, or whether it's even possible. If it is possible, more accurate instructions in the documentation would be nice, and if it's not possible, it should be changed.

**Comment by rubymaniac** [comment]
@emchristiansen I have added some new notes on the Quick Start guide you have to read for getting started using sbt version 0.10.x

**Comment by emchristiansen** [comment]
Thanks @rubymaniac. I think you need to specify the version number in the libraryDependency (just tested it), so I added that. I'm also not sure what the "ondex" repository is for (Scalala builds without it). So I commented it out. Feel free to add it back in if you think it's necessary.
