### ISSUE TITLE
Error occurs during the build of distributable jar

### ISSUE THREAD

**Issue by ghost** [scalala/Scalala#30]
What steps will reproduce the problem?
1. sbt proguard

Following error occurs:

proguard: java.io.IOException: Can't read [/home/andrew/jdk1.7/jre/lib/rt.jar] Can't process class [com/oracle/net/Sdp$1.class](Unsupported version number [51.0] for class format))

What version of the product are you using? On what operating system?

java version "1.7.0"
Java(TM) SE Runtime Environment (build 1.7.0-b147)
Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)

I googled that its because build process invoke proguad 4.6, which dont suppot jdk7, instead of new proguard-4.7

**Comment by dlwh** [comment]
In that case, it's more a bug again the sbt proguard plugin, is it not?

https://github.com/siasia/xsbt-proguard-plugin

**Comment by dramage** [comment]
This has been addressed upstream in the SNAPSHOT repo.

https://github.com/siasia/xsbt-proguard-plugin/issues/8

For now, I changed the plugins.sbt to depend on xsbt-proguard-plugin-0.1-SNAPSHOT so things will build for java 7 users.  Pushed in 693f8c4ebfc.
