### ISSUE TITLE
scalala.library.numerics.erf() is incorrect about 0.0

### ISSUE THREAD

**Issue by duckworthd** [scalala/Scalala#36]
For example,

scala> Numerics.erf(-0.5)
res39: Double = -0.5206970701578215

scala> Numerics.erf(0.0)
res40: Double = 1.0

scala> Numerics.erf(0.5)
res41: Double = 0.5206970701578215

Numerics.erf(0.0) should = 0.0

**Comment by dramage** [comment]
Yikes, you're right we're off by quite a bit here.  I think the broader question is if we ought to be wrapping some other library where other people have worked out the numerical stability of the function approximations or if we should be redoing that work here.  This is originally dlwh's code.  Any opinion, David?

**Comment by duckworthd** [comment]
For this issue I used another approximation off of [wikipedia](http://en.wikipedia.org/wiki/Error_function#Approximation_with_elementary_functions) for erf() and erfi() based on the [cited paper](http://sites.google.com/site/winitzki/sergei-winitzkis-files/erf-approx.pdf).  

https://gist.github.com/1520395

More generally though, it seems that the most popular scientific library for Java is [Michael Flanagan's](http://www.ee.ucl.ac.uk/~mflanaga/java/).  Personally, I don't see any reason not to fall back on a well-tested library for common functions -- the only question is who's willing to implement the necessary changes.

**Comment by dlwh** [comment]
Flanagan's code is a no-go, since it's incompatible with GPL. 

I'll patch the code for now and we'll discuss adding another dependency. Commons or Colt seem like the best options.
