### ISSUE TITLE
Compilation fails when trying to publish-local

### ISSUE THREAD

**Issue by mosesn** [scalala/Scalala#50]
The error that I get is: 

```
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by dlwh** [comment]
You need to provide the scala compiler with more memory. -Xmx2g should cover it.

**Comment by mosesn** [comment]
I was trying with 1g, and it didn't work.  I tried again with 2g, and it still doesn't work.  Here is the command I was using:

```
env JAVA_OPTS="-Xmx2g" sbt publish-local
```

I got it from [stackoverflow](http://stackoverflow.com/a/3870572/284648).  If you know of a better way to set memory, I would be glad to hear it.

**Comment by dlwh** [comment]
Your sbt file is probably overriding the JAVA_OPTS environment. 

vim `which sbt` (or emacs, or whatever)) and change it there.

**Comment by dlwh** [comment]
err `which sbt`

**Comment by mosesn** [comment]
good call, I had forgotten the options were specified by the sbt script.

thanks for the help!
