### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by sbrignone** [scalala/Scalala#53]
Sorry guys, I am a newbe using sbt but I followed the start process and, after a few minutes compiling ('compile' command), I got the following error:

[error] {file:/C:/Users/Public/Documents/scalala-Scalala-5f31329/}default-02f6de/compile:compile: java.io.IOException: C
annot run program "javac": CreateProcess error=2, The system cannot find the file specified

Any help?
Thanks
SB

**Comment by dlwh** [comment]
I think you need to install a JDK (not a JRE)

-- David

On Fri, Apr 20, 2012 at 8:17 AM, sbrignone
reply@reply.github.com
wrote:

**Comment by sbrignone** [comment]
Oh, you are right ... I was not using a JDK as java compiler ...
