### ISSUE TITLE
Can't plot scatter charts with X and Y arguments only

### ISSUE THREAD

**Issue by danielkorzekwa** [scalala/Scalala#58]
To be able to plot scatter chart I need to provide number of arguments in addition to X and Y values.

It should be possible to plot scatter chart simply by typing scatter(X,Y).

Scatter chart example: https://gist.github.com/1288473

**Comment by dlwh** [comment]
We're in the middle of a huge refactoring and it's going to be a while
before we bring back plotting. I'd accept a patch, but that's about
all I can promise in the short term.

-- David

On Tue, Jun 12, 2012 at 4:54 AM, Daniel Korzekwa
reply@reply.github.com
wrote:
