### ISSUE TITLE
Vector Concatenation (Matrix result)

### ISSUE THREAD

**Issue by krux02** [scalala/Scalala#63]
coming with some with background in matlab and glsl, I know it should be easy to concat two Vectors into a Matrix, but this simple example refuses to compile.

scala>  DenseMatrix.horzcat( DenseVectorCol(1,2,3), DenseVectorCol(3,4,5) )
<console>:39: error: type mismatch;
 found   : scalala.tensor.dense.DenseVectorCol[Int]
 required: scalala.tensor.Matrix[?]
               DenseMatrix.horzcat( DenseVectorCol(1,2,3), DenseVectorCol(3,4,5) )
                                                  ^
<console>:39: error: type mismatch;
 found   : scalala.tensor.dense.DenseVectorCol[Int]
 required: scalala.tensor.Matrix[?]
               DenseMatrix.horzcat( DenseVectorCol(1,2,3), DenseVectorCol(3,4,5) )

**Comment by dlwh** [comment]
Scalala is dead. Use breeze instead: https://github.com/dlwh/breeze/wiki/Quickstart
