### ISSUE TITLE
m(i,::) erroneously returns the sum of all elements of m

### ISSUE THREAD

**Issue by afwlehmann** [scalala/Scalala#9]
For two-dimensional tensors, say m, m(i,::) returns the sum of all elements of m regardless of the "selected row", e.g.

scala> val x = DenseMatrix.tabulate[Double](3,3)((i,j) => i*j)
x: scalala.tensor.dense.DenseMatrix[Double] = 
0.0  0.0  0.0  
0.0  1.0  2.0  
0.0  2.0  4.0  

scala> x(1,::).sum  
res18: Double = 9.0

**Comment by dramage** [comment]
Fixed as of https://github.com/scalala/Scalala/commit/44b94693aad30867fa5d83ae99e3870c6a6e2258
